using System.Collections.Generic;
using RimWorld;
using RimWorld.Planet;
using UnityEngine;
using Verse;

namespace RimExodus
{
    /// <summary>
    /// 宿主地图上的无缝地块管理器。
    /// 负责生成/卸载无缝地块口袋地图，并维护接缝关系。
    ///
    /// 阶段3：邻居方向基于世界地块真实顶点角度（动态），不再用固定 0-5 编号。
    /// 多边形裁切用内切圆顶点模型（顶点 = center + 0.5S × 方向）。
    /// 详见阶段3计划。
    /// </summary>
    public class SeamlessTileManager : MapComponent
    {
        /// <summary>
        /// 锚点地图（家园 A）的直接邻居表。口袋地图的邻居表存于自身的 MapParent_SeamlessTile。
        /// 通过 <see cref="SeamlessTileGraph"/> 统一查询，屏蔽存储位置差异。
        /// </summary>
        public List<NeighborLink> neighbors = new List<NeighborLink>();

        /// <summary>是否已自动生成首个邻居地块（原型阶段：开档即生成北侧，便于测试）。</summary>
        private bool autoGeneratedFirstNeighbor;

        /// <summary>延迟生成首个邻居地块的 tick 计数（MapGenerated 时 mapBeingGenerated 仍非空，需延迟到下一 tick）。</summary>
        private int pendingAutoGenerateTicks = -1;

        /// <summary>锚点地图是否已完成多边形虚空铺设（原生地图不走 RimExodus GenStep，需补铺一次）。</summary>
        private bool anchorVoidApplied;

        public SeamlessTileManager(Map map) : base(map)
        {
        }

        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_Values.Look(ref autoGeneratedFirstNeighbor, "autoGeneratedFirstNeighbor");
            Scribe_Values.Look(ref pendingAutoGenerateTicks, "pendingAutoGenerateTicks", -1);
            Scribe_Values.Look(ref anchorVoidApplied, "anchorVoidApplied");

            if (Scribe.mode == LoadSaveMode.Saving)
            {
                neighbors?.RemoveAll(n => n == null || n.neighbor == null);
            }
            Scribe_Collections.Look(ref neighbors, "neighbors", LookMode.Deep);
            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                neighbors ??= new List<NeighborLink>(6);
                neighbors.RemoveAll(n => n == null || n.neighbor == null);
            }
        }

        /// <summary>获取指向 worldTile 的邻居连接（null 表示无此邻居）。</summary>
        public NeighborLink GetNeighborByWorldTile(int targetWorldTile)
        {
            foreach (var link in neighbors)
            {
                if (link != null && link.worldTile == targetWorldTile && link.neighbor != null)
                {
                    return link;
                }
            }
            return null;
        }

        /// <summary>设置指向 worldTile 的邻居连接（覆盖或新增）。</summary>
        public void SetNeighbor(int worldTile, float edgeAngle, MapParent neighbor, IntVec3 offset)
        {
            neighbors.RemoveAll(n => n != null && n.worldTile == worldTile);
            if (neighbor == null) return;
            neighbors.Add(new NeighborLink
            {
                worldTile = worldTile,
                edgeAngle = edgeAngle,
                neighbor = neighbor,
                offset = offset
            });
        }

        public override void MapComponentTick()
        {
            base.MapComponentTick();
            if (pendingAutoGenerateTicks > 0)
            {
                pendingAutoGenerateTicks--;
                if (pendingAutoGenerateTicks == 0)
                {
                    pendingAutoGenerateTicks = -1;
                    TryAutoGenerateFirstNeighbor();
                }
            }
        }

        public override void MapGenerated()
        {
            base.MapGenerated();
            // 仅锚点地图（家园 A）触发自动生成，便于原型测试。
            // 口袋地块的邻居生成不通过 MapGenerated 自动级联（避免生成风暴）。
            if (map.IsPocketMap) return;
            if (!autoGeneratedFirstNeighbor)
            {
                autoGeneratedFirstNeighbor = true;
                pendingAutoGenerateTicks = 1;
            }
        }

        /// <summary>
        /// 自动生成首个世界邻居地块（原型阶段：开档即生成，便于测试渲染与接缝）。
        /// 取家园 A 的第一个世界邻居 tile 作为生成目标。
        /// </summary>
        private void TryAutoGenerateFirstNeighbor()
        {
            var anchorWorldTile = map.Tile;
            if (anchorWorldTile < 0) return;

            var worldNeighbors = new List<PlanetTile>();
            Find.WorldGrid.GetTileNeighbors(anchorWorldTile, worldNeighbors);
            if (worldNeighbors.Count == 0) return;

            // 取第一个尚未生成的世界邻居。
            foreach (var neighborTile in worldNeighbors)
            {
                var neighborId = neighborTile.tileId;
                if (GetNeighborByWorldTile(neighborId) != null) continue;

                // 先确保锚点地图的多边形虚空已铺设。
                EnsureAnchorVoidApplied();

                var mapSize = new IntVec3(map.Size.x, 1, map.Size.z);
                var parent = GenerateTileMap(anchorWorldTile, neighborId, mapSize);
                if (parent != null)
                {
                    Log.Message($"[RimExodus] Auto-generated seamless tile map for world tile {neighborId} (hostOffset={parent.hostOffset}).");
                }
                return; // 仅自动生成第一个
            }
        }

        /// <summary>
        /// 确保锚点地图（家园 A）的多边形虚空已铺设。
        /// 原生地图不走 RimExodus GenStep，需在首次生成邻居前补铺一次。
        /// </summary>
        internal void EnsureAnchorVoidApplied()
        {
            if (map.IsPocketMap) return;
            if (anchorVoidApplied) return;

            var anchorWorldTile = map.Tile;
            if (anchorWorldTile >= 0)
            {
                SeamlessTerrainFill.ApplyPolygonTerrain(map, anchorWorldTile);
            }
            anchorVoidApplied = true;
        }

        /// <summary>
        /// 在锚点地图 sourceMap 的指定方向（世界邻居 newWorldTile）生成一个无缝地块口袋地图。
        /// </summary>
        /// <param name="sourceWorldTile">源地块的世界 tile id</param>
        /// <param name="newWorldTile">新地块的世界 tile id</param>
        /// <param name="mapSize">口袋地图尺寸</param>
        public MapParent_SeamlessTile GenerateTileMap(int sourceWorldTile, int newWorldTile, IntVec3 mapSize)
        {
            if (MapGenerator.mapBeingGenerated != null)
            {
                Log.Warning("[RimExodus] Cannot generate seamless tile map during map generation.");
                return null;
            }

            // 防递归：该世界邻居已有地块则跳过。
            if (GetNeighborByWorldTile(newWorldTile) != null)
            {
                Log.Message($"[RimExodus] World tile {newWorldTile} already has a neighbor on map {map.uniqueID}, skip generation.");
                return null;
            }

            var def = DefDatabase<WorldObjectDef>.GetNamedSilentFail("RimExodus_SeamlessTileMap");
            if (def == null)
            {
                Log.Error("[RimExodus] WorldObjectDef RimExodus_SeamlessTileMap not found.");
                return null;
            }

            var mapParent = (MapParent_SeamlessTile)WorldObjectMaker.MakeWorldObject(def);
            mapParent.mapGenerator = def.mapGenerator;
            mapParent.worldTile = newWorldTile;
            mapParent.Tile = 0;

            // sourceMap 扁平化：始终指向锚点地图（家园 A）。
            var anchorMap = SeamlessTileGraph.GetAnchorMap(map) ?? map;
            mapParent.sourceMap = anchorMap;

            // hostOffset：新地块相对生成源地块（调用者 map）的偏移。
            mapParent.hostOffset = ComputeNeighborOffset(sourceWorldTile, newWorldTile, map);

            var interiorMap = MapGenerator.GenerateMap(mapSize, mapParent, mapParent.MapGeneratorDef,
                mapParent.ExtraGenStepDefs, isPocketMap: true);

            Find.World.pocketMaps.Add(mapParent);

            if (!Find.World.worldObjects.Contains(interiorMap.Parent))
            {
                Find.World.worldObjects.Add(interiorMap.Parent);
            }

            // 共享锚点地图的天空/天气。
            interiorMap.skyManager = anchorMap.skyManager;
            interiorMap.weatherDecider = anchorMap.weatherDecider;
            interiorMap.weatherManager = anchorMap.weatherManager;

            // 双向登记邻居表。
            RegisterNeighborBidirectional(map, mapParent, sourceWorldTile, newWorldTile, mapParent.hostOffset);

            // 自动沿多边形接缝放置传送点对。
            PlaceEnterSpots(mapParent, interiorMap, sourceWorldTile, newWorldTile);

            return mapParent;
        }

        /// <summary>
        /// 计算从 sourceWorldTile 到 newWorldTile，新地块相对源地块的偏移。
        /// offset = round(2 × (边中点 - 中心))，边中点取自源地块多边形（内切圆模型）。
        /// 边由 newWorldTile 在源地块邻居表中的位置确定。
        /// </summary>
        private IntVec3 ComputeNeighborOffset(int sourceWorldTile, int newWorldTile, Map sourceMap)
        {
            var sourceSize = sourceMap.Size;
            var verts = SeamlessPolygonGeometry.BuildPolygonVertices(sourceWorldTile, sourceSize.x);
            if (verts.Count == 0) return IntVec3.Zero;

            var edgeIdx = WorldTileGeometry.FindNeighborIndex(sourceWorldTile, newWorldTile);
            if (edgeIdx < 0) return IntVec3.Zero;

            var n = verts.Count;
            var center = new Vector2(sourceSize.x * 0.5f, sourceSize.z * 0.5f);
            var mid = (verts[edgeIdx] + verts[(edgeIdx + 1) % n]) * 0.5f;
            // 邻居中心 = 中心 + 2 × (边中点 - 中心) = 2×mid - center。
            // offset 语义：邻居本地坐标 + offset = 源地图坐标。
            // 邻居本地原点(0,0) 对应源坐标 = 邻居中心 - S/2 = (2×mid - center) - center + center = 2×mid - center...
            // 简化：邻居中心在源坐标系的偏移量 = 2×(mid - center)。
            // 邻居本地中心(S/2) 映射到源坐标 neighborCenterSource = center + 2×(mid-center)。
            // 故 offset = neighborCenterSource - neighborLocalCenter = (center + 2×(mid-center)) - center = 2×(mid-center)。
            var offsetVec = 2f * (mid - center);
            return new IntVec3(Mathf.RoundToInt(offsetVec.x), 0, Mathf.RoundToInt(offsetVec.y));
        }

        /// <summary>
        /// 双向登记源地块与新地块的邻居关系。
        /// 源地块 → 新地块：用源地块多边形上指向 newWorldTile 的边角度。
        /// 新地块 → 源地块：用新地块多边形上指向 sourceWorldTile 的边角度，偏移 = -offset。
        /// </summary>
        private static void RegisterNeighborBidirectional(Map sourceMap, MapParent_SeamlessTile newParent,
            int sourceWorldTile, int newWorldTile, IntVec3 offset)
        {
            var sourceParent = sourceMap.info.parent;

            // 源地块 → 新地块：边角度取自源地块。
            var sourceEdgeAngle = GetEdgeAngle(sourceWorldTile, newWorldTile);
            if (sourceParent is MapParent_SeamlessTile sourceTileParent)
            {
                sourceTileParent.SetNeighbor(newWorldTile, sourceEdgeAngle, newParent, offset);
            }
            else
            {
                sourceMap.GetComponent<SeamlessTileManager>()?.SetNeighbor(newWorldTile, sourceEdgeAngle, newParent, offset);
            }

            // 新地块 → 源地块：边角度取自新地块，偏移取反。
            var newEdgeAngle = GetEdgeAngle(newWorldTile, sourceWorldTile);
            newParent.SetNeighbor(sourceWorldTile, newEdgeAngle, sourceParent, -offset);
        }

        /// <summary>获取 fromWorldTile 指向 toWorldTile 的边方向角（弧度，atan2(dir.x, dir.y)）。</summary>
        private static float GetEdgeAngle(int fromWorldTile, int toWorldTile)
        {
            var edgeDirs = WorldTileGeometry.ComputeEdgeDirections(fromWorldTile);
            var idx = WorldTileGeometry.FindNeighborIndex(fromWorldTile, toWorldTile);
            if (idx < 0 || idx >= edgeDirs.Count) return 0f;
            var dir = edgeDirs[idx];
            return Mathf.Atan2(dir.x, dir.y);
        }

        /// <summary>
        /// 沿多边形接缝满铺传送点对。
        /// 对每条对应已存在邻居的边，用 Bresenham 划线枚举候选格，放置本端+对端传送点对。
        /// 本端在源地图坐标重合于对端（视觉位置不跳变）。
        /// </summary>
        private void PlaceEnterSpots(MapParent_SeamlessTile parent, Map interiorMap,
            int sourceWorldTile, int newWorldTile)
        {
            var enterSpotDef = DefDatabase<ThingDef>.GetNamedSilentFail("RimExodus_SeamlessEnterSpot");
            if (enterSpotDef == null)
            {
                Log.Error("[RimExodus] ThingDef RimExodus_SeamlessEnterSpot not found.");
                return;
            }

            var sourceSize = map.Size;
            var offset = parent.hostOffset;
            var placed = 0;

            // 源地块多边形顶点（用于接缝划线）。
            var verts = SeamlessPolygonGeometry.BuildPolygonVertices(sourceWorldTile, sourceSize.x);
            if (verts.Count == 0) return;

            var edgeIdx = WorldTileGeometry.FindNeighborIndex(sourceWorldTile, newWorldTile);
            if (edgeIdx < 0) return;

            // 沿边 edgeIdx 划线枚举候选格。
            foreach (var sourceCell in SeamlessPolygonGeometry.EnumerateEdgeCells(verts, edgeIdx, sourceSize.x))
            {
                if (!sourceCell.InBounds(map)) continue;

                // 对端局部坐标 = 源坐标 - hostOffset（两端在源地图坐标系重合）。
                var localCell = SeamlessMapUtility.FromMapCoord(sourceCell, offset);
                // 对端必须可站立：虚空不 Walkable，传送点只铺在可通行侧。
                if (!localCell.InBounds(interiorMap) || !localCell.Walkable(interiorMap)) continue;
                // 源端也须可站立（Pawn 站上去才触发）。
                if (!sourceCell.Walkable(map)) continue;

                var sourceSpot = ThingMaker.MakeThing(enterSpotDef);
                var sourceComp = sourceSpot.TryGetComp<CompSeamlessTileEnterSpot>();
                var tileSpot = ThingMaker.MakeThing(enterSpotDef);
                var tileComp = tileSpot.TryGetComp<CompSeamlessTileEnterSpot>();

                var spawnedSource = GenSpawn.Spawn(sourceSpot, sourceCell, map);
                var spawnedTile = GenSpawn.Spawn(tileSpot, localCell, interiorMap);

                if (spawnedSource != null && spawnedTile != null && sourceComp != null && tileComp != null)
                {
                    sourceComp.CounterpartSpot = tileSpot;
                    tileComp.CounterpartSpot = sourceSpot;
                    placed++;
                }
                else
                {
                    if (spawnedSource != null) spawnedSource.DeSpawn();
                    if (spawnedTile != null) spawnedTile.DeSpawn();
                }
            }

            Log.Message($"[RimExodus] PlaceEnterSpots source={sourceWorldTile} new={newWorldTile} placed {placed} pairs on map {map.uniqueID}<->{interiorMap.uniqueID}, offset={offset}");
        }

        /// <summary>卸载一个无缝地块口袋地图，并清理邻居表中的双向引用。</summary>
        public void RemoveTileMap(MapParent_SeamlessTile parent)
        {
            if (parent == null) return;

            var interiorMap = parent.Map;
            if (interiorMap != null)
            {
                CleanupNeighborLinks(parent);
                parent.sourceMap = null;
                Find.World.pocketMaps.Remove(parent);
                Current.Game.DeinitAndRemoveMap(interiorMap, false);
            }
        }

        /// <summary>移除 parent 与其所有邻居之间的双向邻居表引用。</summary>
        private static void CleanupNeighborLinks(MapParent_SeamlessTile parent)
        {
            var linksToRemove = new List<NeighborLink>(parent.neighbors);
            parent.neighbors.Clear();

            foreach (var link in linksToRemove)
            {
                if (link?.neighbor == null) continue;
                if (link.neighbor is MapParent_SeamlessTile neighborTile)
                {
                    neighborTile.neighbors.RemoveAll(n => n != null && n.neighbor == parent);
                }
                else if (link.neighbor.Map != null)
                {
                    link.neighbor.Map.GetComponent<SeamlessTileManager>()?.neighbors
                        .RemoveAll(n => n != null && n.neighbor == parent);
                }
            }
        }
    }
}
