using System.Collections.Generic;
using RimWorld;
using RimWorld.Planet;
using Verse;

namespace RimExodus
{
    /// <summary>
    /// 宿主地图上的无缝地块管理器。
    /// 负责生成/卸载无缝地块口袋地图，并维护接缝关系。
    ///
    /// 生成流程（参考 VMF GenerateVehicleMap，计划书 1.2）：
    /// 1. 用 WorldObjectMaker.MakeWorldObject 创建 MapParent_SeamlessTile。
    /// 2. 设置 sourceMap = 宿主地图。
    /// 3. 调用 MapGenerator.GenerateMap(..., isPocketMap: true)。
    /// 4. 加入 Find.World.pocketMaps。
    /// </summary>
    public class SeamlessTileManager : MapComponent
    {
        /// <summary>
        /// 接缝重叠带宽度（计划书 1.10 结论 4）。
        /// 对端地图与本地地图在接缝方向上的物理重叠宽度，需容纳传送点对。
        /// 用户确认边界应为 5 格。
        /// </summary>
        public const int DefaultOverlapBand = 5;

        /// <summary>是否已自动生成北侧地块（原型阶段：开档即生成北侧，便于测试）。</summary>
        private bool autoGeneratedNorth;

        /// <summary>延迟生成北侧地块的 tick 计数（MapGenerated 时 mapBeingGenerated 仍非空，需延迟到下一 tick）。</summary>
        private int pendingAutoGenerateTicks = -1;

        /// <summary>
        /// 锚点地图（家园 A）的直接邻居表。口袋地图的邻居表存于自身的 MapParent_SeamlessTile。
        /// 通过 <see cref="SeamlessTileGraph"/> 统一查询，屏蔽存储位置差异。
        /// </summary>
        public List<NeighborLink> neighbors = new List<NeighborLink>(6);

        public SeamlessTileManager(Map map) : base(map)
        {
        }

        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_Values.Look(ref autoGeneratedNorth, "autoGeneratedNorth");
            Scribe_Values.Look(ref pendingAutoGenerateTicks, "pendingAutoGenerateTicks", -1);

            // 邻居表序列化（仅锚点地图上有有效数据）。
            if (Scribe.mode == LoadSaveMode.Saving)
            {
                neighbors?.RemoveAll(n => n == null || n.neighbor == null);
            }
            Scribe_Collections.Look(ref neighbors, "neighbors", LookMode.Deep);
            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                neighbors ??= new List<NeighborLink>(6);
                neighbors.RemoveAll(n => n == null || n.neighbor == null);
            }
        }

        /// <summary>获取指定方向的邻居连接（null 表示该方向无邻居）。</summary>
        public NeighborLink GetNeighborInDirection(int dir)
        {
            if (dir < 0 || dir >= 6)
            {
                return null;
            }
            foreach (var link in neighbors)
            {
                if (link != null && link.direction == dir && link.neighbor != null)
                {
                    return link;
                }
            }
            return null;
        }

        /// <summary>设置指定方向的邻居连接（覆盖或新增）。</summary>
        public void SetNeighbor(int dir, MapParent neighbor, IntVec3 offset)
        {
            neighbors.RemoveAll(n => n != null && n.direction == dir);
            if (neighbor == null)
            {
                return;
            }
            neighbors.Add(new NeighborLink { direction = dir, neighbor = neighbor, offset = offset });
        }

        public override void MapComponentTick()
        {
            base.MapComponentTick();

            // 延迟自动生成北侧地块：MapGenerated() 在 GenerateMap 内部调用，
            // 此时 MapGenerator.mapBeingGenerated 仍非空，GenerateTileMap 会拒绝。
            // 因此延迟到下一 tick 再生成。所有地块都走这条延迟路径。
            if (pendingAutoGenerateTicks > 0)
            {
                pendingAutoGenerateTicks--;
                if (pendingAutoGenerateTicks == 0)
                {
                    pendingAutoGenerateTicks = -1;
                    TryAutoGenerateNorth();
                }
            }
        }

        public override void MapGenerated()
        {
            base.MapGenerated();
            // 开档自动生成北侧地块：仅在锚点地图（家园 A）触发，便于原型测试。
            // 口袋地块的邻居生成不通过 MapGenerated 自动级联（避免生成风暴），
            // 而是由玩家显式命令（Dev 菜单）或未来的"pawn 接近边界"事件驱动。
            // 注意：SeamlessTileManager 会被 Map.FillComponents 实例化到每张地图，
            // 口袋地图生成时也会收到 MapGenerated，此处 IsPocketMap 守门阻止级联。
            if (map.IsPocketMap)
            {
                return;
            }
            if (!autoGeneratedNorth)
            {
                autoGeneratedNorth = true;
                pendingAutoGenerateTicks = 1;
            }
        }

        /// <summary>
        /// 自动生成北侧地块（原型阶段：开档即生成北侧，便于测试渲染与接缝）。
        /// </summary>
        private void TryAutoGenerateNorth()
        {
            if (GetTileMapInDirection(0) != null)
            {
                return;
            }
            var mapSize = new IntVec3(map.Size.x, 1, map.Size.z);
            var overlapBand = DefaultOverlapBand;
            var parent = GenerateTileMap(0, mapSize, overlapBand);
            if (parent != null)
            {
                Log.Message($"[RimExodus] Auto-generated north seamless tile map (hostOffset={parent.hostOffset}).");
            }
        }

        /// <summary>
        /// 在宿主地图的指定方向生成一个无缝地块口袋地图。
        /// </summary>
        /// <param name="direction">六边形方向：0=北,1=东北,2=东南,3=南,4=西南,5=西北（原型四向兼容：1/2→东,4/5→西）</param>
        /// <param name="mapSize">口袋地图尺寸</param>
        /// <param name="overlapBand">接缝重叠带宽度（计划书 1.10 结论 4）</param>
        public MapParent_SeamlessTile GenerateTileMap(int direction, IntVec3 mapSize, int overlapBand)
        {
            if (MapGenerator.mapBeingGenerated != null)
            {
                Log.Warning("[RimExodus] Cannot generate seamless tile map during map generation.");
                return null;
            }

            // 防递归：该方向已有邻居则跳过（替代旧的 IsPocketMap return 禁令）。
            if (GetNeighborInDirection(direction) != null)
            {
                Log.Message($"[RimExodus] Direction {direction} already has a neighbor on map {map.uniqueID}, skip generation.");
                return null;
            }

            var def = DefDatabase<WorldObjectDef>.GetNamedSilentFail("RimExodus_SeamlessTileMap");
            if (def == null)
            {
                Log.Error("[RimExodus] WorldObjectDef RimExodus_SeamlessTileMap not found.");
                return null;
            }

            var mapParent = (MapParent_SeamlessTile)WorldObjectMaker.MakeWorldObject(def);
            mapParent.mapGenerator = def.mapGenerator;
            mapParent.direction = direction;
            mapParent.Tile = 0;

            // sourceMap 扁平化：始终指向锚点地图（家园 A），而非调用者 map。
            // 避免原生嵌套副作用（财富/威胁/移除连带的父子归属误判）。
            // 地块间邻接关系由邻居表维护，不依赖 sourceMap。
            var anchorMap = SeamlessTileGraph.GetAnchorMap(map) ?? map;
            mapParent.sourceMap = anchorMap;

            // hostOffset：新地块相对生成源地块（调用者 map）的偏移。
            // 注意 hostOffset 总是相对"直接源地块"，不是相对锚点。
            mapParent.hostOffset = ComputeHostOffset(direction, mapSize, overlapBand);

            var interiorMap = MapGenerator.GenerateMap(mapSize, mapParent, mapParent.MapGeneratorDef,
                mapParent.ExtraGenStepDefs, isPocketMap: true);

            Find.World.pocketMaps.Add(mapParent);

            if (!Find.World.worldObjects.Contains(interiorMap.Parent))
            {
                Find.World.worldObjects.Add(interiorMap.Parent);
            }

            // 共享锚点地图的天空/天气（所有地块共享同一套）。
            interiorMap.skyManager = anchorMap.skyManager;
            interiorMap.weatherDecider = anchorMap.weatherDecider;
            interiorMap.weatherManager = anchorMap.weatherManager;

            // 双向登记邻居表。
            // 源地块（map）的该方向邻居 = 新地块，偏移 = hostOffset（新地块相对源地块）。
            // 新地块的反方向邻居 = 源地块，偏移 = -hostOffset（源地块相对新地块）。
            RegisterNeighborBidirectional(map, mapParent, direction, mapParent.hostOffset);

            // 自动在接缝重叠带放置传送点对，沿接缝满铺。
            PlaceEnterSpots(mapParent, interiorMap, direction, overlapBand);

            return mapParent;
        }

        /// <summary>
        /// 双向登记源地块与新地块的邻居关系。
        /// 源地块可能是锚点地图（普通 Map，邻居表在 SeamlessTileManager）或口袋地图（邻居表在 MapParent_SeamlessTile）。
        /// NeighborLink.neighbor 为 MapParent 基类，可容纳锚点 MapParent 和 MapParent_SeamlessTile。
        /// </summary>
        private static void RegisterNeighborBidirectional(Map sourceMap, MapParent_SeamlessTile newParent, int direction, IntVec3 offset)
        {
            var oppositeDir = SeamlessTileGraph.OppositeDirection(direction);
            var sourceParent = sourceMap.info.parent; // 源地块的 MapParent（锚点或口袋）。

            // 源地块 → 新地块（源地块坐标系下新地块的偏移 = offset）。
            if (sourceParent is MapParent_SeamlessTile sourceTileParent)
            {
                sourceTileParent.SetNeighbor(direction, newParent, offset);
            }
            else
            {
                // 锚点地图：邻居表存于 SeamlessTileManager。
                sourceMap.GetComponent<SeamlessTileManager>()?.SetNeighbor(direction, newParent, offset);
            }

            // 新地块 → 源地块（新地块坐标系下源地块的偏移 = -offset）。
            newParent.SetNeighbor(oppositeDir, sourceParent, -offset);
        }

        /// <summary>
        /// 沿接缝重叠带满铺传送点对。
        /// 本端传送点挂在源地图（map）上，对端传送点挂在新地块地图（interiorMap）上，
        /// 每对本端/对端在源地图坐标上重合于同一格，保证 Pawn 转移后视觉位置不跳变。
        /// 沿接缝方向每隔一格放一对，跳过边缘 2 格不可通行区。
        /// 传送点是 Ethereal 载体，可与任何地形（岩山/深水/墙）共存，因此源端不再过滤地形。
        /// 但对端必须可站立（Pawn 落地格需 Walkable），否则传送永远失败——该对直接跳过。
        /// </summary>
        private void PlaceEnterSpots(MapParent_SeamlessTile parent, Map interiorMap, int direction, int overlapBand)
        {
            var enterSpotDef = DefDatabase<ThingDef>.GetNamedSilentFail("RimExodus_SeamlessEnterSpot");
            if (enterSpotDef == null)
            {
                Log.Error("[RimExodus] ThingDef RimExodus_SeamlessEnterSpot not found.");
                return;
            }

            var sourceSize = map.Size;
            var offset = parent.hostOffset;
            var placed = 0;

            // 沿接缝方向遍历每个格，在重叠带中央行/列放置传送点对。
            // 北/南接缝：沿 x 轴遍历，z 固定中央行；东/西接缝：沿 z 轴遍历，x 固定中央列。
            var seamCells = EnumerateSeamCells(direction, overlapBand, sourceSize);
            foreach (var sourceCell in seamCells)
            {
                // Ethereal 不占 edifice，可与岩山/深水/墙共存，源端只需在边界内。
                if (!sourceCell.InBounds(map))
                {
                    continue;
                }

                // 对端局部坐标 = 源坐标 - hostOffset（两端在源地图坐标系重合）。
                var localCell = SeamlessMapUtility.FromMapCoord(sourceCell, offset);
                // 对端必须可站立：Pawn 落地格需 Walkable（TryTransferPawn 也会校验），
                // 不可站立的对端意味着该对传送点永远无法使用，跳过不铺。
                if (!localCell.InBounds(interiorMap) || !localCell.Walkable(interiorMap))
                {
                    continue;
                }

                var sourceSpot = ThingMaker.MakeThing(enterSpotDef);
                var sourceComp = sourceSpot.TryGetComp<CompSeamlessTileEnterSpot>();
                var tileSpot = ThingMaker.MakeThing(enterSpotDef);
                var tileComp = tileSpot.TryGetComp<CompSeamlessTileEnterSpot>();

                // 先生成两端 Thing，再建立双向引用，避免 Spawn 失败时引用悬空。
                var spawnedSource = GenSpawn.Spawn(sourceSpot, sourceCell, map);
                var spawnedTile = GenSpawn.Spawn(tileSpot, localCell, interiorMap);

                if (spawnedSource != null && spawnedTile != null && sourceComp != null && tileComp != null)
                {
                    sourceComp.CounterpartSpot = tileSpot;
                    tileComp.CounterpartSpot = sourceSpot;
                    placed++;
                }
                else
                {
                    // 部分生成失败，清理已生成的一端避免悬空传送点。
                    // 传送点 destroyable=false，Destroy 会被拒绝，必须用 DeSpawn 移除。
                    if (spawnedSource != null) spawnedSource.DeSpawn();
                    if (spawnedTile != null) spawnedTile.DeSpawn();
                }
            }

            Log.Message($"[RimExodus] PlaceEnterSpots dir={direction} placed {placed} pairs on map {map.uniqueID}<->{interiorMap.uniqueID}, offset={offset}");
        }

        /// <summary>
        /// 枚举接缝重叠带中央行/列上的候选格子（沿接缝方向，跳过边缘 2 格）。
        /// 北/南接缝（dir 0/3）：z 固定，x 遍历 [2, sizeX-3]。
        /// 东/西接缝（dir 1/2/4/5）：x 固定，z 遍历 [2, sizeZ-3]。
        /// </summary>
        private static IEnumerable<IntVec3> EnumerateSeamCells(int direction, int overlapBand, IntVec3 sourceSize)
        {
            var bandMid = overlapBand / 2;
            switch (direction)
            {
                case 0: // 北
                {
                    var z = sourceSize.z - bandMid;
                    for (var x = 2; x <= sourceSize.x - 3; x++)
                    {
                        yield return new IntVec3(x, 0, z);
                    }
                    break;
                }
                case 3: // 南
                {
                    var z = bandMid;
                    for (var x = 2; x <= sourceSize.x - 3; x++)
                    {
                        yield return new IntVec3(x, 0, z);
                    }
                    break;
                }
                case 1: // 东北（原型暂作东）
                case 2: // 东南（原型暂作东）
                {
                    var x = sourceSize.x - bandMid;
                    for (var z = 2; z <= sourceSize.z - 3; z++)
                    {
                        yield return new IntVec3(x, 0, z);
                    }
                    break;
                }
                case 4: // 西南（原型暂作西）
                case 5: // 西北（原型暂作西）
                {
                    var x = bandMid;
                    for (var z = 2; z <= sourceSize.z - 3; z++)
                    {
                        yield return new IntVec3(x, 0, z);
                    }
                    break;
                }
            }
        }

        /// <summary>
        /// 计算口袋地图相对宿主地图的平移偏移。
        /// 口袋地图放在宿主地图边界之外，并在接缝方向留出重叠带。
        /// 六边形方向：0=北,1=东北,2=东南,3=南,4=西南,5=西北。
        /// 原型阶段四向兼容：1/2 暂时当作东，4/5 暂时当作西。
        /// </summary>
        private IntVec3 ComputeHostOffset(int direction, IntVec3 mapSize, int overlapBand)
        {
            var hostSize = map.Size;
            switch (direction)
            {
                case 0: // 北
                    return new IntVec3(0, 0, hostSize.z - overlapBand);
                case 1: // 东北（原型暂作东）
                case 2: // 东南（原型暂作东）
                    return new IntVec3(hostSize.x - overlapBand, 0, 0);
                case 3: // 南
                    return new IntVec3(0, 0, -mapSize.z + overlapBand);
                case 4: // 西南（原型暂作西）
                case 5: // 西北（原型暂作西）
                    return new IntVec3(-mapSize.x + overlapBand, 0, 0);
                default:
                    return IntVec3.Zero;
            }
        }

        /// <summary>
        /// 查询当前地图指定方向上的直接邻居地块（基于邻居表，对称架构）。
        /// </summary>
        /// <param name="direction">六边形方向：0=北,1=东北,2=东南,3=南,4=西南,5=西北</param>
        public MapParent_SeamlessTile GetTileMapInDirection(int direction)
        {
            NeighborLink link = null;
            if (map.Parent is MapParent_SeamlessTile pocketParent)
            {
                link = pocketParent.GetNeighborInDirection(direction);
            }
            else
            {
                link = GetNeighborInDirection(direction);
            }
            return link?.neighbor as MapParent_SeamlessTile;
        }

        /// <summary>
        /// 卸载一个无缝地块口袋地图，并清理邻居表中的双向引用。
        /// </summary>
        public void RemoveTileMap(MapParent_SeamlessTile parent)
        {
            if (parent == null)
            {
                return;
            }

            var interiorMap = parent.Map;
            if (interiorMap != null)
            {
                // 清理邻居表：从 parent 的所有邻居上移除指向 parent 的链接，再清空 parent 自身。
                CleanupNeighborLinks(parent);

                parent.sourceMap = null;
                Find.World.pocketMaps.Remove(parent);
                Current.Game.DeinitAndRemoveMap(interiorMap, false);
            }
        }

        /// <summary>移除 parent 与其所有邻居之间的双向邻居表引用。</summary>
        private static void CleanupNeighborLinks(MapParent_SeamlessTile parent)
        {
            var linksToRemove = new List<NeighborLink>(parent.neighbors);
            parent.neighbors.Clear();

            foreach (var link in linksToRemove)
            {
                if (link?.neighbor == null)
                {
                    continue;
                }
                // 从邻居侧移除指向 parent 的链接。
                if (link.neighbor is MapParent_SeamlessTile neighborTile)
                {
                    neighborTile.neighbors.RemoveAll(n => n != null && n.neighbor == parent);
                }
                else if (link.neighbor.Map != null)
                {
                    // 锚点地图：邻居表在 SeamlessTileManager 上。
                    link.neighbor.Map.GetComponent<SeamlessTileManager>()?.neighbors
                        .RemoveAll(n => n != null && n.neighbor == parent);
                }
            }
        }
    }
}
